/*
Copyright 2017 Martin Buck

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation the
rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the Software
is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall
be included all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE
OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
*/

//! Module for IO operations of the stl file format

//@todo better error handling instead of yielding partial data

use crate::*;

use std::io::{BufRead, Write};

use core::str::FromStr;

/// Saves an IsMesh3D in the ASCII .stl file format
pub fn save_stl_ascii<M, P, W>(write: &mut W, mesh: &M) -> Result<()>
where
    M: IsMesh3D<P>,
    P: IsBuildable3D,
    W: Write,
{
    write
        .write_all(b"solid STL generated by rust-3d\n")
        .map_err(|e| e.to_error_kind())?;

    for i in 0..mesh.num_faces() {
        let [v1, v2, v3] = mesh.face_vertices(FId { val: i })?;
        let n = mesh.face_normal(FId { val: i })?;
        let buffer = "facet normal ".to_string()
            + &str_exp(&n)
            + "\n"
            + "    outer loop\n"
            + "        vertex "
            + &str_exp(&v1)
            + "\n"
            + "        vertex "
            + &str_exp(&v2)
            + "\n"
            + "        vertex "
            + &str_exp(&v3)
            + "\n"
            + "    endloop\n"
            + "endfacet\n";
        write
            .write_all(buffer.as_bytes())
            .map_err(|e| e.to_error_kind())?;
    }
    write
        .write_all(b"endsolid STL generated by rust-3d\n")
        .map_err(|e| e.to_error_kind())
}

/// Loads a Mesh from ASCII .stl files
pub fn load_stl_ascii<EM, P, R>(read: &mut R, mesh: &mut EM) -> Result<()>
where
    EM: IsFaceEditableMesh<P, Face3> + IsVertexEditableMesh<P, Face3>,
    P: IsBuildable3D + Clone,
    R: BufRead,
{
    let mut line_buffer = String::new();

    // skip 'solid'
    read.read_line(&mut line_buffer)?;

    loop {
        //@todo currently simply stops on error
        if let Ok([a, b, c]) = read_stl_facet(read, &mut line_buffer) {
            mesh.add_face(a, b, c);
        } else {
            break;
        }
    }

    Ok(())
}

fn fetch_line<'a, R>(read: &mut R, line_buffer: &'a mut String) -> Result<&'a str>
where
    R: BufRead,
{
    line_buffer.clear();
    let n_read = read.read_line(line_buffer)?;
    if n_read == 0 {
        return Err(ErrorKind::StlError(StlError::LoadFileEndReached));
    }
    Ok(line_buffer.trim_end())
}

fn read_stl_facet<P, R>(read: &mut R, line_buffer: &mut String) -> Result<[P; 3]>
where
    P: IsBuildable3D,
    R: BufRead,
{
    let mut line: &str;

    line = fetch_line(read, line_buffer)?;
    if !line.contains("facet") {
        return Err(ErrorKind::StlError(StlError::LoadFileInvalid));
    }

    line = fetch_line(read, line_buffer)?;
    if !line.contains("outer loop") {
        return Err(ErrorKind::StlError(StlError::LoadFileInvalid));
    }

    line = fetch_line(read, line_buffer)?;
    let a = read_stl_vertex(&line)?;

    line = fetch_line(read, line_buffer)?;
    let b = read_stl_vertex(&line)?;

    line = fetch_line(read, line_buffer)?;
    let c = read_stl_vertex(&line)?;

    line = fetch_line(read, line_buffer)?;
    if !line.contains("endloop") {
        return Err(ErrorKind::StlError(StlError::LoadFileInvalid));
    }

    line = fetch_line(read, line_buffer)?;
    if !line.contains("endfacet") {
        return Err(ErrorKind::StlError(StlError::LoadFileInvalid));
    }

    Ok([a, b, c])
}

fn read_stl_vertex<P>(line: &str) -> Result<P>
where
    P: IsBuildable3D,
{
    let mut words = to_words(line);

    //@todo fix this error mapping
    // skip "vertex"
    words
        .next()
        .ok_or(ErrorKind::StlError(StlError::LoadFileInvalid))?;

    let x = f64::from_str(
        words
            .next()
            .ok_or(ErrorKind::StlError(StlError::LoadFileInvalid))?,
    )
    .map_err(|_| ErrorKind::StlError(StlError::LoadFileInvalid))?;
    let y = f64::from_str(
        words
            .next()
            .ok_or(ErrorKind::StlError(StlError::LoadFileInvalid))?,
    )
    .map_err(|_| ErrorKind::StlError(StlError::LoadFileInvalid))?;
    let z = f64::from_str(
        words
            .next()
            .ok_or(ErrorKind::StlError(StlError::LoadFileInvalid))?,
    )
    .map_err(|_| ErrorKind::StlError(StlError::LoadFileInvalid))?;

    Ok(P::new(x, y, z))
}

fn str_exp<P>(p: &P) -> String
where
    P: Is3D,
{
    format!("{:e} {:e} {:e}", p.x(), p.y(), p.z()).to_string()
}
